version: '3.7'

networks:
    fzuhelper:
        driver: bridge

services:
  redis:
    container_name: redis
    image: "redis:latest"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=fzuhelper
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      - fzuhelper