// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	empty_room "fzuhelper-empty-room/biz/router/empty_room"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	empty_room.Register(r)

}
