// Code generated by hertz generator.

package empty_room

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _empty_roomMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getemptyroomMw() []app.HandlerFunc {
	// your code...
	return nil
}
